import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import MuiContainer from "@/components/Container";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <MuiContainer>
          {children}
        </MuiContainer>
      </body>
    </html>
  );
}
